import java.awt.Color;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingUtilities;

import Chronotimer.Console;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author dishenwen
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Console con;
    Thread tN;
    Runnable rN;
    boolean numSwitch = false;
    boolean DNFFlag = false;
    boolean timeGet = false;//used so we can know when time is being entered;
    int count1 = 0;//used to keep track of numbers being entered for time;
    int count2 = 0;

   
    public GUI(Console con) {
        this.con=con;
        initComponents();
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        JPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        //set backGround
        JPanel1.setOpaque(true);
        JPanel1.setBackground(Color.getHSBColor(953, 30, 50));
        jPanel2.setBackground(Color.getHSBColor(953, 30, 50));
        jPanel3.setOpaque(true);
        jPanel3.setBackground(Color.getHSBColor(953, 30, 50));
        //
        
        Title = new javax.swing.JLabel();
        J1357Label = new javax.swing.JLabel();
        JStart1 = new javax.swing.JButton();
        JStart3 = new javax.swing.JButton();
        JStart5 = new javax.swing.JButton();
        JStart7 = new javax.swing.JButton();
        JStartLabel = new javax.swing.JLabel();
        J2468Label1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JButton();
        jToggleButton5 = new javax.swing.JButton();
        jToggleButton7 = new javax.swing.JButton();
        JEAble = new javax.swing.JLabel();
        JEAble2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JFinish2 = new javax.swing.JButton();
        JFinish4 = new javax.swing.JButton();
        JFinish6 = new javax.swing.JButton();
        JFinish8 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JButton();
        jToggleButton4 = new javax.swing.JButton();
        jToggleButton6 = new javax.swing.JButton();
        jToggleButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPrinterDisplay = new javax.swing.JTextArea();
        jDisplay = new javax.swing.JTextArea();
        jQRFTime = new javax.swing.JLabel();
        
        jNum1 = new javax.swing.JButton();
        jNum2 = new javax.swing.JButton();
        jNum3 = new javax.swing.JButton();
        jNum4 = new javax.swing.JButton();
        jNum5 = new javax.swing.JButton();
        jNum6 = new javax.swing.JButton();
        jNum7 = new javax.swing.JButton();
        jNum8 = new javax.swing.JButton();
        jNum9 = new javax.swing.JButton();
        jNumStar = new javax.swing.JButton();
        jNum0 = new javax.swing.JButton();
        jNumPound = new javax.swing.JButton();
        jFunction = new javax.swing.JButton();
        jSwap = new javax.swing.JButton();
        jChan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        J2468Label2 = new javax.swing.JLabel();
        J1357Label1 = new javax.swing.JLabel();
        jPower = new javax.swing.JToggleButton();
        jPrinterPwr = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MeFile = new javax.swing.JMenu();
        MeExit = new javax.swing.JMenuItem();
        
        JScrollPane scrollPane = new JScrollPane(jPrinterDisplay);
        scrollPane.setBounds(10,60,780,500);
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        
        
        jDisplay.setEditable(false);
        
        jUp = new javax.swing.JButton();
        jLeft = new javax.swing.JButton();
        jRight = new javax.swing.JButton();
        jDown = new javax.swing.JButton();
        
        jCh1 = new javax.swing.JComboBox<>();
        jCh3 = new javax.swing.JComboBox<>();
        jCh5 = new javax.swing.JComboBox<>();
        jCh7 = new javax.swing.JComboBox<>();
        jCh2 = new javax.swing.JComboBox<>();
        jCh4 = new javax.swing.JComboBox<>();
        jCh6 = new javax.swing.JComboBox<>();
        jCh8 = new javax.swing.JComboBox<>();
        
        Num="";
        
        /*shouldnt start a thread right away because there is race to run
        rN = new displayTextUpdater(jDisplay, con);
        tN = new Thread(rN);
        tN.start();*/
        
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("   CHRONOTIMER 1009");
        Title.setToolTipText("");

        J1357Label.setText("       1                   3                  5                  7");

        JStart1.setText("         ");
        JStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JStart1ActionPerformed(evt);
            }
        });

        JStart3.setText("         ");
        JStart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JStart3ActionPerformed(evt);
            }
        });

        JStart5.setText("         ");
        JStart5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JStart5ActionPerformed(evt);
            }
        });

        JStart7.setText("         ");
        JStart7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JStart7ActionPerformed(evt);
            }
        });

        JStartLabel.setText("Start");

        J2468Label1.setText("       2                   4                  6                  8");

        jToggleButton1.setText("OFF");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("OFF");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton5.setText("OFF");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton7.setText("OFF");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        JEAble.setText("Enable/Disable");

        JEAble2.setText("Enable/Disable");

        jLabel3.setText("Finish");

        JFinish2.setText("         ");
        JFinish2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFinish2ActionPerformed(evt);
            }
        });

        JFinish4.setText("         ");
        JFinish4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFinish4ActionPerformed(evt);
            }
        });

        JFinish6.setText("         ");
        JFinish6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFinish6ActionPerformed(evt);
            }
        });

        JFinish8.setText("         ");
        JFinish8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFinish8ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("OFF");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("OFF");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton6.setText("OFF");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton8.setText("OFF");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jPrinterDisplay.setEditable(false);
        jPrinterDisplay.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createCompoundBorder()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        jDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jQRFTime.setText("Queue/Running/Final Time");

        jNum1.setText("1");
        jNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum1ActionPerformed(evt);
            }
        });

        jNum2.setText("2");
        jNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum2ActionPerformed(evt);
            }
        });

        jNum3.setText("3");
        jNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum3ActionPerformed(evt);
            }
        });

        jNum4.setText("4");
        jNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum4ActionPerformed(evt);
            }
        });

        jNum5.setText("5");
        jNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum5ActionPerformed(evt);
            }
        });

        jNum6.setText("6");
        jNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum6ActionPerformed(evt);
            }
        });

        jNum7.setText("7");
        jNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum7ActionPerformed(evt);
            }
        });

        jNum8.setText("8");
        jNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum8ActionPerformed(evt);
            }
        });

        jNum9.setText("9");
        jNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum9ActionPerformed(evt);
            }
        });

        jNumStar.setText("*");
        jNumStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumStarActionPerformed(evt);
            }
        });

        jNum0.setText("0");
        jNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum0ActionPerformed(evt);
            }
        });

        jNumPound.setText("#");
        jNumPound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumPoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNumStar)
                    .addComponent(jNum7)
                    .addComponent(jNum4)
                    .addComponent(jNum1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jNum2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNum3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jNum5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNum6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jNum8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNum9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jNum0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNumPound)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumStar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumPound, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jFunction.setText("FUNCTION");
        jFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFunctionActionPerformed(evt);
            }
        });

        jSwap.setText("SWAP");
        jSwap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSwapActionPerformed(evt);
            }
        });

        jChan.setText("CHAN");

        J2468Label2.setText("         2                     4                    6                    8");

        J1357Label1.setText("         1                     3                    5                    7");
        

        jCh1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "EYE", "GATE", "PAD" }));
        jCh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCh1ActionPerformed(evt);
            }
        });

        jCh3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "EYE", "GATE", "PAD" }));
        jCh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCh3ActionPerformed(evt);
            }
        });

        jCh5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "EYE", "GATE", "PAD" }));
        jCh5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCh5ActionPerformed(evt);
            }
        });

        jCh7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "EYE", "GATE", "PAD" }));
        jCh7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCh7ActionPerformed(evt);
            }
        });

        jCh2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "EYE", "GATE", "PAD" }));
        jCh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCh2ActionPerformed(evt);
            }
        });

        jCh4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "EYE", "GATE", "PAD" }));
        jCh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCh4ActionPerformed(evt);
            }
        });

        jCh6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "EYE", "GATE", "PAD" }));
        jCh6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCh6ActionPerformed(evt);
            }
        });

        jCh8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "EYE", "GATE", "PAD" }));
        jCh8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCh8ActionPerformed(evt);
            }
        });
        
        
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(J1357Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J2468Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    
                    
                    //modify start
                    .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jCh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCh3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCh5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCh7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jCh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCh4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCh6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCh8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))	
                    
                    
                	//modify end	
                		
                		
                		)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(J1357Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
               
                //modify start
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jCh3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jCh5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jCh7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addComponent(J2468Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCh4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCh6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCh8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                
                // modify end
                
               
                
                
                
                .addGap(16, 16, 16))
        );

        jPower.setForeground(new java.awt.Color(255, 0, 0));
        jPower.setText("Power:OFF");
        jPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPowerActionPerformed(evt);
            }
        });

        jPrinterPwr.setForeground(new java.awt.Color(0, 51, 204));
        jPrinterPwr.setText("Printer Pwr:OFF");
        jPrinterPwr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrinterPwrActionPerformed(evt);
            }
        });
        
        jUp.setText("^");
        jUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpActionPerformed(evt);
            }
        });

        jLeft.setText("<");
        jLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLeftActionPerformed(evt);
            }
        });

        jRight.setText(">");
        jRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRightActionPerformed(evt);
            }
        });

        jDown.setText("v");
        jDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDownActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPower, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(JEAble2)
                            .addComponent(JStartLabel)
                            .addComponent(JEAble)))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSwap)
                            .addComponent(jFunction))))
                .addGap(89, 89, 89)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addComponent(J1357Label, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JFinish2)
                                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(JFinish4)
                                        .addGap(18, 18, 18)
                                        .addComponent(JFinish6)
                                        .addGap(18, 18, 18)
                                        .addComponent(JFinish8))
                                    .addGroup(JPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(J2468Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addComponent(JStart1)
                                .addGap(18, 18, 18)
                                .addComponent(JStart3)
                                .addGap(18, 18, 18)
                                .addComponent(JStart5)
                                .addGap(18, 18, 18)
                                .addComponent(JStart7))
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18,18, 18)
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPrinterPwr, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(JPanel1Layout.createParallelGroup()
                		  .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                		.addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jChan))
                        
    //modify start
                        .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jUp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JPanel1Layout.createSequentialGroup()
                                        .addComponent(jLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDown, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRight, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                		  
                       
    //modify end                  
                        
                        
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        		.addGap(650, 650, 650)
                            .addComponent(jQRFTime)
                            .addComponent(jDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPower, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addComponent(jPrinterPwr, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J1357Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JStart3)
                            .addComponent(JStart5)
                            .addComponent(JStart7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JStartLabel)
                                .addComponent(JStart1)))
                        .addGap(4, 4, 4)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton1)
                            .addComponent(jToggleButton3)
                            .addComponent(jToggleButton5)
                            .addComponent(jToggleButton7)
                            .addComponent(JEAble))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J2468Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JFinish2)
                            .addComponent(JFinish4)
                            .addComponent(JFinish6)
                            .addComponent(JFinish8))
                        .addGap(5, 5, 5)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton2)
                            .addComponent(JEAble2)
                            .addComponent(jToggleButton4)
                            .addComponent(jToggleButton6)
                            .addComponent(jToggleButton8)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addComponent(jFunction)
                                .addGap(18, 18, 18)
                                .addComponent(jSwap)
                                
 //modify start                           		
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jUp)
                                .addGap(5, 5, 5)
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLeft)
                                    .addComponent(jDown)
                                    .addComponent(jRight))))
                        
 //modify end                       
                        
                        
                        
                        
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jQRFTime)
                            .addComponent(jChan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        MeFile.setText("Menu");

        MeExit.setText("Exit");
        MeExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeExitActionPerformed(evt);
            }
        });
        MeFile.add(MeExit);

        jMenuBar1.add(MeFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               
                .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MeExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeExitActionPerformed
    	System.out.println("GUI exiting");
    	System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_MeExitActionPerformed


    private void JStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JStart1ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(1).Trig();
    	}
    }//GEN-LAST:event_JStart1ActionPerformed

    private void JFinish2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFinish2ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(2).Trig();
    	}
    }//GEN-LAST:event_JFinish2ActionPerformed

    private void JStart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JStart3ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(3).Trig();
    	}
    }//GEN-LAST:event_JStart3ActionPerformed

    private void JFinish4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFinish4ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(4).Trig();
    	}
    }//GEN-LAST:event_JFinish4ActionPerformed
    
    private void JStart5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JStart5ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(5).Trig();
    	}
    }//GEN-LAST:event_JStart5ActionPerformed

    private void JFinish6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFinish6ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(6).Trig();
    	}
    }//GEN-LAST:event_JFinish6ActionPerformed

    private void JStart7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JStart7ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(7).Trig();
    	}
    }//GEN-LAST:event_JStart7ActionPerformed

    private void JFinish8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFinish8ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(8).Trig();
    	}
    }//GEN-LAST:event_JFinish8ActionPerformed

    //we want to display the current num generated into the display
    private void jNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum1ActionPerformed
    	 if(con.onCheck()){
    		 if(!timeGet){
    			 Num+="1";
     			jDisplay.setText("Num: " + Num);
    		 }
    		 else{
    			if(count1 < 2){
    				Num+="1";
    				count1++;
    				jDisplay.setText("Time: " + Num);
    			}
    		 }
         }
    }//GEN-LAST:event_jNum1ActionPerformed

    private void jNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum2ActionPerformed
    	 if(con.onCheck()){
    		 if(!timeGet){
    			 Num+="2";
     			jDisplay.setText("Num: " + Num);
    		 }
    		 else{
     			if(count1 < 2){
     				Num+="2";
     				count1++;
     				jDisplay.setText("Time: " + Num);
     			}
     		 }
         }
    }//GEN-LAST:event_jNum2ActionPerformed

    private void jNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum3ActionPerformed
    	 if(con.onCheck()){
    		 if(!timeGet){
    			 Num+="3";
     			jDisplay.setText("Num: " + Num);
    		 }
    		 else{
     			if(count1 < 2){
     				Num+="3";
     				count1++;
     				jDisplay.setText("Time: " + Num);
     			}
     		 }
         }
    }//GEN-LAST:event_jNum3ActionPerformed

    private void jNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum4ActionPerformed
    	 if(con.onCheck()){
    		 if(!timeGet){
    			 Num+="4";
     			jDisplay.setText("Num: " + Num);
    		 }
    		 else{
     			if(count1 < 2){
     				Num+="4";
     				count1++;
     				jDisplay.setText("Time: " + Num);
     			}
     		 }
         }
    }//GEN-LAST:event_jNum4ActionPerformed

    private void jNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum5ActionPerformed
    	 if(con.onCheck()){
    		 if(!timeGet){
    			 Num+="5";
     			jDisplay.setText("Num: " + Num);
    		 }
    		 else{
     			if(count1 < 2){
     				Num+="5";
     				count1++;
     				jDisplay.setText("Time: " + Num);
     			}
     		 }
         }
    }//GEN-LAST:event_jNum5ActionPerformed

    private void jNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum6ActionPerformed
    	 if(con.onCheck()){
    		 if(!timeGet){
    			 Num+="6";
     			jDisplay.setText("Num: " + Num);
    		 }
    		 else{
     			if(count1 < 2){
     				Num+="6";
     				count1++;
     				jDisplay.setText("Time: " + Num);
     			}
     		 }
         }
    }//GEN-LAST:event_jNum6ActionPerformed

    private void jNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum7ActionPerformed
    	 if(con.onCheck()){
    		 if(!timeGet){
    			 Num+="7";
     			jDisplay.setText("Num: " + Num);
    		 }
    		 else{
     			if(count1 < 2){
     				Num+="7";
     				count1++;
     				jDisplay.setText("Time: " + Num);
     			}
     		 }
    	}
    }//GEN-LAST:event_jNum7ActionPerformed

    private void jNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum8ActionPerformed
    	 if(con.onCheck()){
    		 if(!timeGet){
    			 Num+="8";
     			jDisplay.setText("Num: " + Num);
    		 }
    		 else{
     			if(count1 < 2){
     				Num+="8";
     				count1++;
     				jDisplay.setText("Time: " + Num);
     			}
     		 }
         }
    }//GEN-LAST:event_jNum8ActionPerformed

    private void jNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum9ActionPerformed
        if(con.onCheck()){
        	if(!timeGet){
   				Num+="9";
    			jDisplay.setText("Num: " + Num);
        	}
        	else{
    			if(count1 < 2){
    				Num+="9";
    				count1++;
    				jDisplay.setText("Time: " + Num);
    			}
    		 }
        }
    }//GEN-LAST:event_jNum9ActionPerformed

    private void jNumStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumStarActionPerformed
    	if(con.powerState==true){
    		if(!timeGet){
    			con.getChannels().getCh(1).Trig();//another shorthand for trig 1
    		}
    		else{
    			if(count2 < 2){
    				count2++;
    				Num+=":";
    			}
    			else if(count2 == 2){
    				Num+=".";
    			}
    			count1 = 0;
    			jDisplay.setText("Time: " + Num);
    		}
        }
    }//GEN-LAST:event_jNumStarActionPerformed

    private void jNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum0ActionPerformed
        if(con.onCheck()){
        	if(!timeGet){
   			 	Num+="0";
    			jDisplay.setText("Num: " + Num);
   		 	}
        	else{
    			if(count1 < 2){
    				Num+="0";
    				jDisplay.setText("Time: " + Num);
    				count1++;
    			}
    		 }
        }
    }//GEN-LAST:event_jNum0ActionPerformed

    private void jNumPoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumPoundActionPerformed
        //the first time the button is pressed it will start reading a number 
    	if(con.onCheck()){
    		if(con.getDisplayState()){
    			if(con.isMenuOn()){
    				con.closeMenu();//we dont need this anymore
    			}
    			if(DNFFlag){
    				numSwitch = !numSwitch;
    				if(numSwitch == true){
    					tN.interrupt();//it might be inactive so nothing to interrupt //but ensure we do incase display list is shown 
    					Num = "";
    					jDisplay.setText("Num: ");
    				}
    				else{
    					((displayTextUpdater) rN).ExitInterrupt();//else if we came from display list exit the interrupt cycle
						if(!Num.equals("")){
							int id = Integer.parseInt(Num); // turning power off should reset this function
							con.DNF(id); 
							DNFFlag = false;
						}
    				}
    			}
    			else{
    				numSwitch = !numSwitch;
    				if(numSwitch == true){
    					tN.interrupt();//it might be inactive so nothing to interrupt //but ensure we do incase display list is shown 
    					Num = "";
    					jDisplay.setText("Num: ");
    				}	
    	
    				else{//the second time it is pressed it will run the the num command from console
    					/*
    					if(!con.getDisplayState()){// if we werent in the display list go back to running screen
    						con.changeDisplayState();
    						rN = new displayTextUpdater(jDisplay, con);//must start the thread over since fucntion had killed it
    						tN = new Thread(rN);
    						tN.start();
    					}*/
    					((displayTextUpdater) rN).ExitInterrupt();//else if we came from display list exit the interrupt cycle
    					if(!Num.equals("")){
    						int id = Integer.parseInt(Num); // turning power off should reset this function
    						con.Num(id); 
    					}
    				}
    			}
    		}
    		else{//if no run is currently on then we can change the time
    			if(timeGet){
    				numSwitch = !numSwitch;
    				if(numSwitch){
    					//tN.interrupt();
    					Num ="";
    					jDisplay.setText("Time: ");
    				}
    				else{
    					//((displayTextUpdater) rN).ExitInterrupt();
    					timeGet=false;
    					//ensure Num is in the right format
    					con.Time(Num);
    					con.openMenu();
    					count1=0;
    					count2=0;
    					jDisplay.setText(con.getMenu());
    				}
    			}
    			
    		}
    	}

    }//GEN-LAST:event_jNumPoundActionPerformed
    
    private void jFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFunctionActionPerformed
    	if(con.getDisplayState()){//if menu is off
    		if(!con.isMenuOn()){
    			tN.interrupt();
    			con.openMenu();
    			jDisplay.setText(con.getMenu());
    		}
    		else{
    			con.closeMenu();
    			((displayTextUpdater) rN).ExitInterrupt();
    			
    		}
    	}
    	else{//start menu over
    		if(con.isMenuOn()){
    			con.closeMenu();
    		}
    		con.openMenu();
    		jDisplay.setText(con.getMenu());
    	}
    	//else stay in menu as nothing else to display
    	/*
    	con.changeDisplayState();
    	if(!con.getDisplayState()){//if false that means we are in the menu
    		try {
				tN.join();//ensure thread ends
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
    		con.instantiateMenu();
    		jDisplay.setText(con.getMenu());
    	}
    	else{//should start a new thread to display the thread
    		con.closeMenu();
    		rN = new displayTextUpdater(jDisplay, con);
    		tN = new Thread(rN);
    		tN.start();
    	}*/
    }//GEN-LAST:event_jFunctionActionPerformed
    

    private void jCh1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    	if(jCh1.getSelectedItem().equals("EYE"))
    	{
    		if(con.getChannels().getCh(1).isSensor()==true)
    		{
    			con.getChannels().getCh(1).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(1).connect("EYE");
    		}
    		
    	}
    	else if(jCh1.getSelectedItem().equals("GATE"))
    	{
    		if(con.getChannels().getCh(1).isSensor()==true)
    		{
    			con.getChannels().getCh(1).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(1).connect("GATE");
    		}
    		
    		
    	}
    	else if(jCh1.getSelectedItem().equals("PAD"))
    	{
    		if(con.getChannels().getCh(1).isSensor()==true)
    		{
    			con.getChannels().getCh(1).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(1).connect("PAD");
    		}
    		
    		
    	}
    	else if(jCh1.getSelectedItem().equals("None"))
    	{
    		if(con.getChannels().getCh(1).isSensor()==true)
    		{
    			con.getChannels().getCh(1).removeSens();
    		}
    		else
    		{
    			JOptionPane.showMessageDialog(jCh1, "No sensor was armed");
    		}
    		
    		
    	}
    	
    	
    	
    }                                    

    private void jCh3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       	if(jCh3.getSelectedItem().equals("EYE"))
    	{
    		if(con.getChannels().getCh(3).isSensor()==true)
    		{
    			con.getChannels().getCh(3).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(3).connect("EYE");
    		}
    		
    	}
    	else if(jCh3.getSelectedItem().equals("GATE"))
    	{
    		if(con.getChannels().getCh(3).isSensor()==true)
    		{
    			con.getChannels().getCh(3).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(3).connect("GATE");
    		}
    		
    		
    	}
    	else if(jCh3.getSelectedItem().equals("PAD"))
    	{
    		if(con.getChannels().getCh(3).isSensor()==true)
    		{
    			con.getChannels().getCh(3).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(3).connect("PAD");
    		}
    		
    		
    	}
    	else if(jCh3.getSelectedItem().equals("None"))
    	{
    		if(con.getChannels().getCh(3).isSensor()==true)
    		{
    			con.getChannels().getCh(3).removeSens();
    		}
    		else
    		{
    			JOptionPane.showMessageDialog(jCh3, "No sensor was armed");
    		}
    		
    		
    	}
    	
    }                                    

    private void jCh5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       	if(jCh5.getSelectedItem().equals("EYE"))
    	{
    		if(con.getChannels().getCh(5).isSensor()==true)
    		{
    			con.getChannels().getCh(5).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(5).connect("EYE");
    		}
    		
    	}
    	else if(jCh5.getSelectedItem().equals("GATE"))
    	{
    		if(con.getChannels().getCh(5).isSensor()==true)
    		{
    			con.getChannels().getCh(5).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(5).connect("GATE");
    		}
    		
    		
    	}
    	else if(jCh5.getSelectedItem().equals("PAD"))
    	{
    		if(con.getChannels().getCh(5).isSensor()==true)
    		{
    			con.getChannels().getCh(5).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(5).connect("PAD");
    		}
    		
    		
    	}
    	else if(jCh5.getSelectedItem().equals("None"))
    	{
    		if(con.getChannels().getCh(5).isSensor()==true)
    		{
    			con.getChannels().getCh(5).removeSens();
    		}
    		else
    		{
    			JOptionPane.showMessageDialog(jCh5, "No sensor was armed");
    		}
    		
    		
    	}
    	
    }                                    

    private void jCh7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       	if(jCh7.getSelectedItem().equals("EYE"))
    	{
    		if(con.getChannels().getCh(7).isSensor()==true)
    		{
    			con.getChannels().getCh(7).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(7).connect("EYE");
    		}
    		
    	}
    	else if(jCh7.getSelectedItem().equals("GATE"))
    	{
    		if(con.getChannels().getCh(7).isSensor()==true)
    		{
    			con.getChannels().getCh(7).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(7).connect("GATE");
    		}
    		
    		
    	}
    	else if(jCh7.getSelectedItem().equals("PAD"))
    	{
    		if(con.getChannels().getCh(7).isSensor()==true)
    		{
    			con.getChannels().getCh(7).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(7).connect("PAD");
    		}
    		
    		
    	}
    	else if(jCh7.getSelectedItem().equals("None"))
    	{
    		if(con.getChannels().getCh(7).isSensor()==true)
    		{
    			con.getChannels().getCh(7).removeSens();
    		}
    		else
    		{
    			JOptionPane.showMessageDialog(jCh7, "No sensor was armed");
    		}
    		
    		
    	}
    	
    }                                    

    private void jCh2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       	if(jCh2.getSelectedItem().equals("EYE"))
    	{
    		if(con.getChannels().getCh(2).isSensor()==true)
    		{
    			con.getChannels().getCh(2).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(2).connect("EYE");
    		}
    		
    	}
    	else if(jCh2.getSelectedItem().equals("GATE"))
    	{
    		if(con.getChannels().getCh(2).isSensor()==true)
    		{
    			con.getChannels().getCh(2).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(2).connect("GATE");
    		}
    		
    		
    	}
    	else if(jCh2.getSelectedItem().equals("PAD"))
    	{
    		if(con.getChannels().getCh(2).isSensor()==true)
    		{
    			con.getChannels().getCh(2).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(2).connect("PAD");
    		}
    		
    		
    	}
    	else if(jCh2.getSelectedItem().equals("None"))
    	{
    		if(con.getChannels().getCh(2).isSensor()==true)
    		{
    			con.getChannels().getCh(2).removeSens();
    		}
    		else
    		{
    			JOptionPane.showMessageDialog(jCh2, "No sensor was armed");
    		}
    		
    		
    	}
    	
    }                                    

    private void jCh4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       	if(jCh4.getSelectedItem().equals("EYE"))
    	{
    		if(con.getChannels().getCh(4).isSensor()==true)
    		{
    			con.getChannels().getCh(4).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(4).connect("EYE");
    		}
    		
    	}
    	else if(jCh4.getSelectedItem().equals("GATE"))
    	{
    		if(con.getChannels().getCh(4).isSensor()==true)
    		{
    			con.getChannels().getCh(4).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(4).connect("GATE");
    		}
    		
    		
    	}
    	else if(jCh4.getSelectedItem().equals("PAD"))
    	{
    		if(con.getChannels().getCh(4).isSensor()==true)
    		{
    			con.getChannels().getCh(4).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(4).connect("PAD");
    		}
    		
    		
    	}
    	else if(jCh4.getSelectedItem().equals("None"))
    	{
    		if(con.getChannels().getCh(4).isSensor()==true)
    		{
    			con.getChannels().getCh(4).removeSens();
    		}
    		else
    		{
    			JOptionPane.showMessageDialog(jCh4, "No sensor was armed");
    		}
    		
    		
    	}
    	
    }                                    

    private void jCh6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       	if(jCh6.getSelectedItem().equals("EYE"))
    	{
    		if(con.getChannels().getCh(6).isSensor()==true)
    		{
    			con.getChannels().getCh(6).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(6).connect("EYE");
    		}
    		
    	}
    	else if(jCh6.getSelectedItem().equals("GATE"))
    	{
    		if(con.getChannels().getCh(6).isSensor()==true)
    		{
    			con.getChannels().getCh(6).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(6).connect("GATE");
    		}
    		
    		
    	}
    	else if(jCh6.getSelectedItem().equals("PAD"))
    	{
    		if(con.getChannels().getCh(6).isSensor()==true)
    		{
    			con.getChannels().getCh(6).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(6).connect("PAD");
    		}
    		
    		
    	}
    	else if(jCh6.getSelectedItem().equals("None"))
    	{
    		if(con.getChannels().getCh(6).isSensor()==true)
    		{
    			con.getChannels().getCh(6).removeSens();
    		}
    		else
    		{
    			JOptionPane.showMessageDialog(jCh6, "No sensor was armed");
    		}
    		
    		
    	}
    	
    }                                    

    private void jCh8ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       	if(jCh8.getSelectedItem().equals("EYE"))
    	{
    		if(con.getChannels().getCh(8).isSensor()==true)
    		{
    			con.getChannels().getCh(8).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(8).connect("EYE");
    		}
    		
    	}
    	else if(jCh8.getSelectedItem().equals("GATE"))
    	{
    		if(con.getChannels().getCh(8).isSensor()==true)
    		{
    			con.getChannels().getCh(8).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(8).connect("GATE");
    		}
    		
    		
    	}
    	else if(jCh8.getSelectedItem().equals("PAD"))
    	{
    		if(con.getChannels().getCh(8).isSensor()==true)
    		{
    			con.getChannels().getCh(8).removeSens();
    		}
    		else
    		{
    			con.getChannels().getCh(8).connect("PAD");
    		}
    		
    		
    	}
    	else if(jCh8.getSelectedItem().equals("None"))
    	{
    		if(con.getChannels().getCh(8).isSensor()==true)
    		{
    			con.getChannels().getCh(8).removeSens();
    		}
    		else
    		{
    			JOptionPane.showMessageDialog(jCh8, "No sensor was armed");
    		}
    		
    		
    	}
    	
    }                  
    
    
    private void jUpActionPerformed(java.awt.event.ActionEvent evt) {   
    	if(con.onCheck()){
    		if(con.isMenuOn()){
    			con.menuUP();
    			jDisplay.setText(con.getMenu());
    		}
    	}
        // TODO add your handling code here:
    }  
    private void jDownActionPerformed(java.awt.event.ActionEvent evt) { 
    	if(con.onCheck()){
    		if(con.isMenuOn()){
    			con.menuDOWN();
    			jDisplay.setText(con.getMenu());
    		}
    	}
        // TODO add your handling code here:
    }  
    
    private void jRightActionPerformed(java.awt.event.ActionEvent evt) {     
    	if(con.onCheck()){
    		if(con.isMenuOn()){
    			//String currentState = con.getMenu();
    			con.menuRIGHT();
    			String currentState = con.getLastMenu();
    			String nextState = con.getMenu();
    			String x;
    			switch(nextState){
    				case("print"):
    					if(con.printerOnCheck()){
    						jPrinterDisplay.setText(con.Print());
    					}
    					else{
    						jDisplay.setText(currentState +"\n\n\nThe printer is off");
    					}
    					break;
    				case("export"):
    					try {
    						con.export();
    					} catch (IOException e) {
    						// TODO Auto-generated catch block
    						e.printStackTrace();
    					}
    					break;
    				case("ind"):
    					x = con.Event("IND");
    					jDisplay.setText(currentState + "\n\n\n" + x);
    					break;
    				case("parind"):
    					x = con.Event("PARIND");
						jDisplay.setText(currentState + "\n\n\n" + x);
    					break;
    				case("grp"):
    					x = con.Event("GROUP");
						jDisplay.setText(currentState + "\n\n\n" + x);
    					break;
    				case("paragrp"):
    					jDisplay.setText(currentState + "\n\n\nUNAVAILABLE");
    					break;
    				case("dnf"):
    					if(con.getRaceType().equals("GROUP")){
    						jDisplay.setText("Num: ");
    						DNFFlag = true;
    						//press pound first
    					}
    					else{
    						con.DNF();
    					}
    					break;
    				case("cancel"):
    					con.Cancel();
    					break;
    				case("newrun"):
    					x = con.newRun();//will turn on displayState /therefore a thread can be started
    					if(x.equals("")){
    						con.closeMenu();
    						rN = new displayTextUpdater(jDisplay, con);
    						tN = new Thread(rN);
    						tN.start();
    						/*try {
								SwingUtilities.invokeAndWait(new displayTextUpdater(jDisplay,con));
							} catch (InvocationTargetException e) {
								// TODO Auto-generated catch block
								e.printStackTrace();
							} catch (InterruptedException e) {
								// TODO Auto-generated catch block
								e.printStackTrace();
							}*/
    					}
    					else{
    						jDisplay.setText(currentState + "\n\n\n" + x);
    					}
    					break;
    				case("endrun"):
    					x = con.endRun();
    					if(con.getDisplayState()){//display list must bre true because a run is on
    						//will close displayState so we can wait for it to exit
    						((displayTextUpdater) rN).ExitInterrupt();//exit interrupt from menu
    						try {
    							tN.join();//join displayList thread
    						} catch (InterruptedException e) {
    							e.printStackTrace();
    						}
    					}
    					jDisplay.setText(currentState + "\n\n\n" + x);
    					break;
    				case("time"):
    					//must press num to enter num;
    					//press num again finish entering
    					if(!con.getDisplayState()){//can only change time if there is not current run
    						timeGet = true;//we are taking time
    						jDisplay.setText("Press # to enter a time in format xx:xx:xx.xx\npress * to enter:");//press # to enter time
    						con.closeMenu();
    					}
    					else{
    						jDisplay.setText(currentState + "\n\n\nCan't change timer during an event");
    					}
    					break;
    				case("exit"):
    					if(con.getDisplayState()){//if a list can be displayed display it
    						con.closeMenu();
    						((displayTextUpdater) rN).ExitInterrupt();
    					}
    					//else stay here
    					/*
    					con.changeDisplayState();
    					rN = new displayTextUpdater(jDisplay, con);
    					tN = new Thread(rN);
    					tN.start();
    					*/
    					break;
    				case("reset"):
    					con.closeMenu();
    					con.Reset();
    					if(con.getDisplayState()){
    						((displayTextUpdater) rN).ExitInterrupt();//exit interrupt from menu
    						try {
    							tN.join();//join displayList thread
    						} catch (InterruptedException e) {
    							e.printStackTrace();
    						}
    					}
    					PowerOFFUpdate();
    					jPrinterDisplay.setText("");
    					jPrinterPwr.setText("Printer Pwr: OFF");
    					jDisplay.setText(con.getMenu());
    					break;
    				default:
    					jDisplay.setText(nextState);
    					break;
    			}
    		}
    	}
        // TODO add your handling code here:
    }  
    
    private void jLeftActionPerformed(java.awt.event.ActionEvent evt) {   
    	if(con.onCheck()){
    		if(con.isMenuOn()){
    			con.menuLEFT();
    			String nextState = con.getMenu();
    			if(nextState.equals("exit")){
    				if(con.getDisplayState()){//if list to be displayed is available display it
    					con.closeMenu();
    					((displayTextUpdater) rN).ExitInterrupt();
    				}
    				
    				//else stay here
    				/*
    				con.closeMenu();
    				con.changeDisplayState();
					rN = new displayTextUpdater(jDisplay, con);
					tN = new Thread(rN);
					tN.start();
					*/
					
    			}else{
    				jDisplay.setText(nextState);
    			}
    		}
    	}
        // TODO add your handling code here:
    }  

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(1);
    		if(con.isConnected(1)){
    			jToggleButton1.setText("ON");
    		}
    		else{
    			jToggleButton1.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton1ActionPerformed

        
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
                // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(2);
    		if(con.isConnected(2)){
    			jToggleButton2.setText("ON");
    		}
    		else{
    			jToggleButton2.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(3);
    		if(con.isConnected(3)){
    			jToggleButton3.setText("ON");
    		}
    		else{
    			jToggleButton3.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(4);
    		if(con.isConnected(4)){
    			jToggleButton4.setText("ON");
    		}
    		else{
    			jToggleButton4.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    
    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(5);
    		if(con.isConnected(5)){
    			jToggleButton5.setText("ON");
    		}
    		else{
    			jToggleButton5.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(6);
    		if(con.isConnected(6)){
    			jToggleButton6.setText("ON");
    		}
    		else{
    			jToggleButton6.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(7);
    		if(con.isConnected(7)){
    			jToggleButton7.setText("ON");
    		}
    		else{
    			jToggleButton7.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(8);
    		if(con.isConnected(8)){
    			jToggleButton8.setText("ON");
    		}
    		else{
    			jToggleButton8.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void PowerOFFUpdate()
    {
    	jToggleButton1.setText("OFF");
    	jToggleButton2.setText("OFF");
    	jToggleButton3.setText("OFF");
    	jToggleButton4.setText("OFF");
    	jToggleButton5.setText("OFF");
    	jToggleButton6.setText("OFF");
    	jToggleButton7.setText("OFF");
    	jToggleButton8.setText("OFF");
    	jDisplay.setText("");
    	if(con.printerOnCheck()){
    		con.printerPower();//turn off
    		jPrinterPwr.setText("Printer Pwr:OFF");
        	jPrinterDisplay.setText("");
    	}
    	
    }
    
    private void jPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowerActionPerformed
        // TODO add your handling code here:
    	
    	if(jPower.isSelected())
        {
            jPower.setText("Power:ON");
            con.Power();
            jDisplay.setText(con.getMenu());//first thing to see is the menu
          /*
            if(con.getDisplayState() == false){
            	con.changeDisplayState();
            	 rN = new displayTextUpdater(jDisplay, con);
                 tN = new Thread(rN);
                 tN.start();
            }
           */
          
        }
        else
        {
            jPower.setText("Power:OFF");
            PowerOFFUpdate();
            numSwitch = false;//reset numpad reading
            con.Power();
        }
    	
    }//GEN-LAST:event_jPowerActionPerformed

    private void jPrinterPwrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrinterPwrActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	if(!con.printerOnCheck())//if printer off turn it on
        {
            jPrinterPwr.setText("Printer Pwr:ON");
            con.printerPower();
        }
        else
        {
            jPrinterPwr.setText("Printer Pwr:OFF");
            con.printerPower();
            jPrinterDisplay.setText("");
        }
    	}
    }//GEN-LAST:event_jPrinterPwrActionPerformed

   

    private void jSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSwapActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.Swap();	
    	}
    }//GEN-LAST:event_jSwapActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI(null).setVisible(true);
            }
        });
    }
	*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J1357Label;
    private javax.swing.JLabel J1357Label1;
    private javax.swing.JLabel J2468Label1;
    private javax.swing.JLabel J2468Label2;
    private javax.swing.JLabel JEAble;
    private javax.swing.JLabel JEAble2;
    private javax.swing.JButton JFinish2;
    private javax.swing.JButton JFinish4;
    private javax.swing.JButton JFinish6;
    private javax.swing.JButton JFinish8;
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton JStart1;
    private javax.swing.JButton JStart3;
    private javax.swing.JButton JStart5;
    private javax.swing.JButton JStart7;
    private javax.swing.JLabel JStartLabel;
    private javax.swing.JMenuItem MeExit;
    private javax.swing.JMenu MeFile;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jChan;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private JTextArea jDisplay;
    private javax.swing.JButton jFunction;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jNum0;
    private javax.swing.JButton jNum1;
    private javax.swing.JButton jNum2;
    private javax.swing.JButton jNum3;
    private javax.swing.JButton jNum4;
    private javax.swing.JButton jNum5;
    private javax.swing.JButton jNum6;
    private javax.swing.JButton jNum7;
    private javax.swing.JButton jNum8;
    private javax.swing.JButton jNum9;
    private javax.swing.JButton jNumPound;
    private javax.swing.JButton jNumStar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jPower;
    private JTextArea jPrinterDisplay;
    private javax.swing.JButton jPrinterPwr;
    private javax.swing.JLabel jQRFTime;
    private javax.swing.JButton jSwap;
    private javax.swing.JButton jToggleButton1;
    private javax.swing.JButton jToggleButton2;
    private javax.swing.JButton jToggleButton3;
    private javax.swing.JButton jToggleButton4;
    private javax.swing.JButton jToggleButton5;
    private javax.swing.JButton jToggleButton6;
    private javax.swing.JButton jToggleButton7;
    private javax.swing.JButton jToggleButton8;
    private javax.swing.JButton jUp;
    private javax.swing.JButton jDown;
    private javax.swing.JButton jRight;
    private javax.swing.JButton jLeft;
    private String Num;
    private javax.swing.JComboBox<String> jCh1;
    private javax.swing.JComboBox<String> jCh2;
    private javax.swing.JComboBox<String> jCh3;
    private javax.swing.JComboBox<String> jCh4;
    private javax.swing.JComboBox<String> jCh5;
    private javax.swing.JComboBox<String> jCh6;
    private javax.swing.JComboBox<String> jCh7;
    private javax.swing.JComboBox<String> jCh8;
    
    
    // End of variables declaration//GEN-END:variables
}
