import javax.swing.JTextArea;

import Chronotimer.Console;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author dishenwen
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Console con;
    Thread tN;
    Runnable rN;
    public GUI(Console con) {
        this.con=con;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        JPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        J1357Label = new javax.swing.JLabel();
        JStart1 = new javax.swing.JButton();
        JStart3 = new javax.swing.JButton();
        JStart5 = new javax.swing.JButton();
        JStart7 = new javax.swing.JButton();
        JStartLabel = new javax.swing.JLabel();
        J2468Label1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JButton();
        jToggleButton5 = new javax.swing.JButton();
        jToggleButton7 = new javax.swing.JButton();
        JEAble = new javax.swing.JLabel();
        JEAble2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JFinish2 = new javax.swing.JButton();
        JFinish4 = new javax.swing.JButton();
        JFinish6 = new javax.swing.JButton();
        JFinish8 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JButton();
        jToggleButton4 = new javax.swing.JButton();
        jToggleButton6 = new javax.swing.JButton();
        jToggleButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPrinterDisplay = new javax.swing.JLabel();
        jDisplay = new javax.swing.JTextArea();
        jQRFTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jNum1 = new javax.swing.JButton();
        jNum2 = new javax.swing.JButton();
        jNum3 = new javax.swing.JButton();
        jNum4 = new javax.swing.JButton();
        jNum5 = new javax.swing.JButton();
        jNum6 = new javax.swing.JButton();
        jNum7 = new javax.swing.JButton();
        jNum8 = new javax.swing.JButton();
        jNum9 = new javax.swing.JButton();
        jNumStar = new javax.swing.JButton();
        jNum0 = new javax.swing.JButton();
        jNumPound = new javax.swing.JButton();
        jFunction = new javax.swing.JButton();
        jSwap = new javax.swing.JButton();
        jChan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        J2468Label2 = new javax.swing.JLabel();
        J1357Label1 = new javax.swing.JLabel();
        jPower = new javax.swing.JToggleButton();
        jPrinterPwr = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MeFile = new javax.swing.JMenu();
        MeExit = new javax.swing.JMenuItem();
        
        rN = new displayTextUpdater(jDisplay, con);
        tN = new Thread(rN);
        jUp = new javax.swing.JButton();
        jLeft = new javax.swing.JButton();
        jRight = new javax.swing.JButton();
        jDown = new javax.swing.JButton();
        
        Num="";
        
        
        tN.start();
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("   CHRONOTIMER 1009");
        Title.setToolTipText("");

        J1357Label.setText("       1                   3                  5                  7");

        JStart1.setText("         ");
        JStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JStart1ActionPerformed(evt);
            }
        });

        JStart3.setText("         ");
        JStart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JStart3ActionPerformed(evt);
            }
        });

        JStart5.setText("         ");
        JStart5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JStart5ActionPerformed(evt);
            }
        });

        JStart7.setText("         ");
        JStart7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JStart7ActionPerformed(evt);
            }
        });

        JStartLabel.setText("Start");

        J2468Label1.setText("       2                   4                  6                  8");

        jToggleButton1.setText("OFF");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("OFF");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton5.setText("OFF");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton7.setText("OFF");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        JEAble.setText("Enable/Disable");

        JEAble2.setText("Enable/Disable");

        jLabel3.setText("Finish");

        JFinish2.setText("         ");
        JFinish2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFinish2ActionPerformed(evt);
            }
        });

        JFinish4.setText("         ");
        JFinish4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFinish4ActionPerformed(evt);
            }
        });

        JFinish6.setText("         ");
        JFinish6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFinish6ActionPerformed(evt);
            }
        });

        JFinish8.setText("         ");
        JFinish8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFinish8ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("OFF");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("OFF");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton6.setText("OFF");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton8.setText("OFF");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jPrinterDisplay.setText("Printer");
        jPrinterDisplay.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createCompoundBorder()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPrinterDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPrinterDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        jDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jQRFTime.setText("Queue/Running/Final Time");

        jNum1.setText("1");
        jNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum1ActionPerformed(evt);
            }
        });

        jNum2.setText("2");
        jNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum2ActionPerformed(evt);
            }
        });

        jNum3.setText("3");
        jNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum3ActionPerformed(evt);
            }
        });

        jNum4.setText("4");
        jNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum4ActionPerformed(evt);
            }
        });

        jNum5.setText("5");
        jNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum5ActionPerformed(evt);
            }
        });

        jNum6.setText("6");
        jNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum6ActionPerformed(evt);
            }
        });

        jNum7.setText("7");
        jNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum7ActionPerformed(evt);
            }
        });

        jNum8.setText("8");
        jNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum8ActionPerformed(evt);
            }
        });

        jNum9.setText("9");
        jNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum9ActionPerformed(evt);
            }
        });

        jNumStar.setText("*");
        jNumStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumStarActionPerformed(evt);
            }
        });

        jNum0.setText("0");
        jNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNum0ActionPerformed(evt);
            }
        });

        jNumPound.setText("#");
        jNumPound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumPoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNumStar)
                    .addComponent(jNum7)
                    .addComponent(jNum4)
                    .addComponent(jNum1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jNum2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNum3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jNum5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNum6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jNum8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNum9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jNum0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNumPound)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumStar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumPound, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jFunction.setText("FUNCTION");
        jFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFunctionActionPerformed(evt);
            }
        });

        jSwap.setText("SWAP");
        jSwap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSwapActionPerformed(evt);
            }
        });

        jChan.setText("CHAN");

        J2468Label2.setText("         2                     4                    6                    8");

        J1357Label1.setText("         1                     3                    5                    7");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(J1357Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J2468Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(J1357Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(J2468Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jPower.setForeground(new java.awt.Color(255, 0, 0));
        jPower.setText("Power:OFF");
        jPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPowerActionPerformed(evt);
            }
        });

        jPrinterPwr.setForeground(new java.awt.Color(0, 51, 204));
        jPrinterPwr.setText("Printer Pwr:OFF");
        jPrinterPwr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrinterPwrActionPerformed(evt);
            }
        });
        
        jUp.setText("UP");
        jUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpActionPerformed(evt);
            }
        });

        jLeft.setText("<");
        jLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLeftActionPerformed(evt);
            }
        });

        jRight.setText(">");
        jRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRightActionPerformed(evt);
            }
        });

        jDown.setText("Down");
        jDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDownActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPower, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(JEAble2)
                            .addComponent(JStartLabel)
                            .addComponent(JEAble)))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSwap)
                            .addComponent(jFunction))))
                .addGap(89, 89, 89)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addComponent(J1357Label, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JFinish2)
                                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(JFinish4)
                                        .addGap(18, 18, 18)
                                        .addComponent(JFinish6)
                                        .addGap(18, 18, 18)
                                        .addComponent(JFinish8))
                                    .addGroup(JPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(J2468Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addComponent(JStart1)
                                .addGap(18, 18, 18)
                                .addComponent(JStart3)
                                .addGap(18, 18, 18)
                                .addComponent(JStart5)
                                .addGap(18, 18, 18)
                                .addComponent(JStart7))
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18,18, 18)
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPrinterPwr, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(JPanel1Layout.createParallelGroup()
                		  .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                		.addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jChan))
                        
    //modify start
                        .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jUp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JPanel1Layout.createSequentialGroup()
                                        .addComponent(jLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDown, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRight, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                		  
                       
    //modify end                  
                        
                        
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        		.addGap(650, 650, 650)
                            .addComponent(jQRFTime)
                            .addComponent(jDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPower, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addComponent(jPrinterPwr, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J1357Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JStart3)
                            .addComponent(JStart5)
                            .addComponent(JStart7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JStartLabel)
                                .addComponent(JStart1)))
                        .addGap(4, 4, 4)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton1)
                            .addComponent(jToggleButton3)
                            .addComponent(jToggleButton5)
                            .addComponent(jToggleButton7)
                            .addComponent(JEAble))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J2468Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JFinish2)
                            .addComponent(JFinish4)
                            .addComponent(JFinish6)
                            .addComponent(JFinish8))
                        .addGap(5, 5, 5)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton2)
                            .addComponent(JEAble2)
                            .addComponent(jToggleButton4)
                            .addComponent(jToggleButton6)
                            .addComponent(jToggleButton8)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addComponent(jFunction)
                                .addGap(18, 18, 18)
                                .addComponent(jSwap)
                                
 //modify start                           		
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jUp)
                                .addGap(5, 5, 5)
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLeft)
                                    .addComponent(jDown)
                                    .addComponent(jRight))))
                        
 //modify end                       
                        
                        
                        
                        
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jQRFTime)
                            .addComponent(jChan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        MeFile.setText("Menu");

        MeExit.setText("Exit");
        MeExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeExitActionPerformed(evt);
            }
        });
        MeFile.add(MeExit);

        jMenuBar1.add(MeFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MeExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeExitActionPerformed
     System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_MeExitActionPerformed


    private void JStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JStart1ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(1).Trig();
    	}
    }//GEN-LAST:event_JStart1ActionPerformed

    private void JFinish2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFinish2ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(2).Trig();
    	}
    }//GEN-LAST:event_JFinish2ActionPerformed

    private void JStart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JStart3ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(3).Trig();
    	}
    }//GEN-LAST:event_JStart3ActionPerformed

    private void JFinish4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFinish4ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(4).Trig();
    	}
    }//GEN-LAST:event_JFinish4ActionPerformed
    
    private void JStart5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JStart5ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(5).Trig();
    	}
    }//GEN-LAST:event_JStart5ActionPerformed

    private void JFinish6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFinish6ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(6).Trig();
    	}
    }//GEN-LAST:event_JFinish6ActionPerformed

    private void JStart7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JStart7ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(7).Trig();
    	}
    }//GEN-LAST:event_JStart7ActionPerformed

    private void JFinish8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFinish8ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.getChannels().getCh(8).Trig();
    	}
    }//GEN-LAST:event_JFinish8ActionPerformed

    private void jNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum1ActionPerformed
        // TODO add your handling code here:
    	Num+="1";
    }//GEN-LAST:event_jNum1ActionPerformed

    private void jNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum2ActionPerformed
        // TODO add your handling code here:
    	Num+="2";
    }//GEN-LAST:event_jNum2ActionPerformed

    private void jNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum3ActionPerformed
        // TODO add your handling code here:
    	Num+="3";
    }//GEN-LAST:event_jNum3ActionPerformed

    private void jNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum4ActionPerformed
        // TODO add your handling code here:
    	Num+="4";
    }//GEN-LAST:event_jNum4ActionPerformed

    private void jNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum5ActionPerformed
        // TODO add your handling code here:
    	Num+="5";
    }//GEN-LAST:event_jNum5ActionPerformed

    private void jNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum6ActionPerformed
        // TODO add your handling code here:
    	Num+="6";
    }//GEN-LAST:event_jNum6ActionPerformed

    private void jNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum7ActionPerformed
        // TODO add your handling code here:
    	Num+="7";
    }//GEN-LAST:event_jNum7ActionPerformed

    private void jNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum8ActionPerformed
        // TODO add your handling code here:
    	Num+="8";
    }//GEN-LAST:event_jNum8ActionPerformed

    private void jNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum9ActionPerformed
        // TODO add your handling code here:
    	Num+="9";
    }//GEN-LAST:event_jNum9ActionPerformed

    private void jNumStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumStarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumStarActionPerformed

    private void jNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNum0ActionPerformed
        // TODO add your handling code here:
    	Num+="0";
    }//GEN-LAST:event_jNum0ActionPerformed

    private void jNumPoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumPoundActionPerformed
        // TODO add your handling code here:
    	int cnt = Integer.parseInt(Num);
    	Num="";
    	con.Num(cnt);

    }//GEN-LAST:event_jNumPoundActionPerformed
    
    private void jFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFunctionActionPerformed
        // TODO add your handling code here:
    	con.changeDisplayState();
    	if(!con.getDisplayState()){//if false that means we are in the menu
    		try {
				tN.join();//ensure thread ends
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    		jDisplay.setText(con.getMenu());
    	}
    	else{//should start a new thread to display the thread
    		rN = new displayTextUpdater(jDisplay, con);
    		tN = new Thread(rN);
    		tN.start();
    	}
    }//GEN-LAST:event_jFunctionActionPerformed
    
    private void jUpActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }  
    private void jDownActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }  
    
    private void jRightActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }  
    
    private void jLeftActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }  

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(1);
    		if(con.isConnected(1)){
    			jToggleButton1.setText("ON");
    		}
    		else{
    			jToggleButton1.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton1ActionPerformed

        
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
                // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(2);
    		if(con.isConnected(2)){
    			jToggleButton2.setText("ON");
    		}
    		else{
    			jToggleButton2.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(3);
    		if(con.isConnected(3)){
    			jToggleButton3.setText("ON");
    		}
    		else{
    			jToggleButton3.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(4);
    		if(con.isConnected(4)){
    			jToggleButton4.setText("ON");
    		}
    		else{
    			jToggleButton4.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    
    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(5);
    		if(con.isConnected(5)){
    			jToggleButton5.setText("ON");
    		}
    		else{
    			jToggleButton5.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(6);
    		if(con.isConnected(6)){
    			jToggleButton6.setText("ON");
    		}
    		else{
    			jToggleButton6.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(7);
    		if(con.isConnected(7)){
    			jToggleButton7.setText("ON");
    		}
    		else{
    			jToggleButton7.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    		con.Tog(8);
    		if(con.isConnected(8)){
    			jToggleButton8.setText("ON");
    		}
    		else{
    			jToggleButton8.setText("OFF");
    		}
    	}
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void PowerOFFUpdate()
    {
    	jToggleButton1.setText("OFF");
    	jToggleButton2.setText("OFF");
    	jToggleButton3.setText("OFF");
    	jToggleButton4.setText("OFF");
    	jToggleButton5.setText("OFF");
    	jToggleButton6.setText("OFF");
    	jToggleButton7.setText("OFF");
    	jToggleButton8.setText("OFF");
    }
    
    private void jPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowerActionPerformed
        // TODO add your handling code here:
    	
    	if(jPower.isSelected())
        {
            jPower.setText("Power:ON");
            con.Power();
        }
        else
        {
            jPower.setText("Power:OFF");
            PowerOFFUpdate();
            
            con.Power();
        }
    	
    }//GEN-LAST:event_jPowerActionPerformed

    private void jPrinterPwrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrinterPwrActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	if(jPrinterPwr.isSelected())
        {
            jPrinterPwr.setText("Printer Pwr:ON");
            con.printer.Power();
        }
        else
        {
            jPrinterPwr.setText("Printer Pwr:OFF");
            con.printer.Power();
        }
    	}
    }//GEN-LAST:event_jPrinterPwrActionPerformed

   

    private void jSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSwapActionPerformed
        // TODO add your handling code here:
    	if(con.powerState==true){
    	con.Swap();	
    	}
    }//GEN-LAST:event_jSwapActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI(null).setVisible(true);
            }
        });
    }
	*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J1357Label;
    private javax.swing.JLabel J1357Label1;
    private javax.swing.JLabel J2468Label1;
    private javax.swing.JLabel J2468Label2;
    private javax.swing.JLabel JEAble;
    private javax.swing.JLabel JEAble2;
    private javax.swing.JButton JFinish2;
    private javax.swing.JButton JFinish4;
    private javax.swing.JButton JFinish6;
    private javax.swing.JButton JFinish8;
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton JStart1;
    private javax.swing.JButton JStart3;
    private javax.swing.JButton JStart5;
    private javax.swing.JButton JStart7;
    private javax.swing.JLabel JStartLabel;
    private javax.swing.JMenuItem MeExit;
    private javax.swing.JMenu MeFile;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jChan;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private JTextArea jDisplay;
    private javax.swing.JButton jFunction;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jNum0;
    private javax.swing.JButton jNum1;
    private javax.swing.JButton jNum2;
    private javax.swing.JButton jNum3;
    private javax.swing.JButton jNum4;
    private javax.swing.JButton jNum5;
    private javax.swing.JButton jNum6;
    private javax.swing.JButton jNum7;
    private javax.swing.JButton jNum8;
    private javax.swing.JButton jNum9;
    private javax.swing.JButton jNumPound;
    private javax.swing.JButton jNumStar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jPower;
    private javax.swing.JLabel jPrinterDisplay;
    private javax.swing.JToggleButton jPrinterPwr;
    private javax.swing.JLabel jQRFTime;
    private javax.swing.JButton jSwap;
    private javax.swing.JButton jToggleButton1;
    private javax.swing.JButton jToggleButton2;
    private javax.swing.JButton jToggleButton3;
    private javax.swing.JButton jToggleButton4;
    private javax.swing.JButton jToggleButton5;
    private javax.swing.JButton jToggleButton6;
    private javax.swing.JButton jToggleButton7;
    private javax.swing.JButton jToggleButton8;
    private javax.swing.JButton jUp;
    private javax.swing.JButton jDown;
    private javax.swing.JButton jRight;
    private javax.swing.JButton jLeft;
    private String Num;
    
    // End of variables declaration//GEN-END:variables
}
